In [1]:
import pandas as pd

In [2]:
# load dataset
df = pd.read_csv('combined_dataset.csv')

In [3]:
df.head()

,model_2008,displ_2008,cyl_2008,trans_2008,drive_2008,fuel_2008,veh_class_2008,air_pollut_2008,city_mpg_2008,hwy_mpg_2008,...,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,SUV,7.0,15.0,20.0,...,SemiAuto-9,2WD,Gasoline,small SUV,3.0,19.0,27.0,22.0,4,No
1,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,SUV,7.0,15.0,20.0,...,SemiAuto-9,2WD,Gasoline,small SUV,3.0,20.0,27.0,23.0,5,No
2,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,SUV,7.0,15.0,20.0,...,SemiAuto-9,4WD,Gasoline,small SUV,3.0,18.0,26.0,21.0,4,No
3,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,SUV,7.0,15.0,20.0,...,SemiAuto-9,4WD,Gasoline,small SUV,3.0,19.0,26.0,22.0,4,No
4,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,SUV,7.0,17.0,22.0,...,SemiAuto-6,2WD,Gasoline,small SUV,3.0,20.0,28.0,23.0,5,No

In [4]:
df.columns

Index(['model_2008', 'displ_2008', 'cyl_2008', 'trans_2008', 'drive_2008',
       'fuel_2008', 'veh_class_2008', 'air_pollut_2008', 'city_mpg_2008',
       'hwy_mpg_2008', 'cmb_mpg_2008', 'greenhouse_2008', 'smartway_2008',
       'model', 'displ', 'cyl', 'trans', 'drive', 'fuel', 'veh_class',
       'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg',
       'greenhouse_gas_score', 'smartway'],
      dtype='object')

### Q5: For all of the models that were produced in 2008 that are still being produced now, how much has the mpg improved and which vehicle improved the most?

1. Create a new dataframe,` model_mpg`, that contain the mean combined mpg values in 2008 and 2018 for each unique model
To do this, group by model and find the mean cmb_mpg_2008 and mean cmb_mpg for each.

2. Create a new column, mpg_change, with the change in mpg
Subtract the mean mpg in 2008 from that in 2018 to get the change in mpg

3. Find the vehicle that improved the most
Find the max mpg change, and then use query or indexing to see what model it is!

In [9]:
## 1
model_mpg = df.groupby(['model_2008', 'model'])['cmb_mpg_2008', 'cmb_mpg'].mean()
model_mpg

,,cmb_mpg_2008,cmb_mpg
model_2008,model,,
ACURA MDX,ACURA MDX,17.000000,22.000000
ACURA RDX,ACURA RDX,19.000000,22.500000
AUDI A3,AUDI A3,23.333333,28.000000
AUDI A4,AUDI A4,21.000000,27.000000
AUDI A6,AUDI A6,19.666667,25.666667
AUDI A8 L,AUDI A8 L,16.500000,20.500000
AUDI Q7,AUDI Q7,15.000000,21.000000
AUDI R8,AUDI R8,15.000000,17.500000
AUDI S4,AUDI S4,15.500000,24.000000
AUDI S5,AUDI S5,16.000000,24.000000
AUDI S6,AUDI S6,16.000000,18.000000
AUDI S8,AUDI S8,15.000000,18.000000
AUDI TT Coupe,AUDI TT Coupe,21.666667,26.000000
AUDI TT Roadster,AUDI TT Roadster,21.333333,26.000000
BMW 750i,BMW 750i,20.000000,19.500000
BMW Alpina B7,BMW Alpina B7,18.000000,19.000000
BMW M6 Convertible,BMW M6 Convertible,14.000000,16.500000
BUICK Enclave,BUICK Enclave,18.500000,20.500000
CADILLAC CTS,CADILLAC CTS,20.000000,22.800000
CADILLAC Escalade,CADILLAC Escalade,14.000000,17.000000
CHEVROLET Corvette,CHEVROLET Corvette,18.000000,17.750000
CHEVROLET Equinox,CHEVROLET Equinox,19.000000,27.833333
CHEVROLET Impala,CHEVROLET Impala,20.500000,21.250000
CHEVROLET Malibu,CHEVROLET Malibu,22.333333,33.000000
CHEVROLET Silverado 15,CHEVROLET Silverado 15,16.000000,17.111111
CHEVROLET Tahoe 1500,CHEVROLET Tahoe 1500,14.000000,16.875000
CHRYSLER 300,CHRYSLER 300,18.800000,20.000000
CHRYSLER Pacifica,CHRYSLER Pacifica,17.333333,22.000000
DODGE Challenger,DODGE Challenger,15.000000,19.000000
DODGE Charger,DODGE Charger,18.800000,19.750000
...,...,...,...
NISSAN Pathfinder,NISSAN Pathfinder,15.500000,22.500000
NISSAN Versa,NISSAN Versa,28.000000,31.400000
PORSCHE 911 GT3,PORSCHE 911 GT3,18.000000,16.500000
PORSCHE 911 Turbo,PORSCHE 911 Turbo,18.000000,21.000000
PORSCHE 911 Turbo Cabriolet,PORSCHE 911 Turbo Cabriolet,18.000000,21.000000
PORSCHE Boxster,PORSCHE Boxster,22.000000,24.500000
PORSCHE Boxster S,PORSCHE Boxster S,21.000000,23.000000
PORSCHE Cayenne,PORSCHE Cayenne,16.000000,20.000000
PORSCHE Cayenne S,PORSCHE Cayenne S,15.000000,20.000000
PORSCHE Cayman,PORSCHE Cayman,22.000000,24.500000
PORSCHE Cayman S,PORSCHE Cayman S,21.000000,23.000000
ROLLS-ROYCE Phantom,ROLLS-ROYCE Phantom,15.000000,14.000000
SUBARU Forester,SUBARU Forester,21.500000,25.666667
SUBARU Impreza,SUBARU Impreza,21.750000,29.000000
SUBARU Legacy,SUBARU Legacy,21.125000,26.000000
TOYOTA 4Runner,TOYOTA 4Runner,16.750000,18.000000
TOYOTA Avalon,TOYOTA Avalon,22.000000,24.000000
TOYOTA Camry,TOYOTA Camry,24.250000,30.000000
TOYOTA Corolla,TOYOTA Corolla,30.000000,31.000000
TOYOTA Highlander,TOYOTA Highlander,19.500000,22.000000
TOYOTA Land Cruiser,TOYOTA Land Cruiser,15.000000,15.000000
TOYOTA RAV4,TOYOTA RAV4,22.250000,25.000000
TOYOTA Sequoia,TOYOTA Sequoia,14.750000,14.500000
TOYOTA Tundra,TOYOTA Tundra,15.400000,15.250000
TOYOTA Yaris,TOYOTA Yaris,31.500000,32.500000
VOLKSWAGEN GTI,VOLKSWAGEN GTI,24.500000,27.500000
VOLKSWAGEN Jetta,VOLKSWAGEN Jetta,24.166667,30.000000
VOLKSWAGEN Passat,VOLKSWAGEN Passat,21.250000,25.500000
VOLVO S60,VOLVO S60,21.333333,27.000000
VOLVO XC 90,VOLVO XC 90,15.666667,32.200000

In [14]:
a = model_mpg.set_index(append = True, list(range(len(model_mpg['mpg_change']))))
a.head(2)

SyntaxError: positional argument follows keyword argument (<ipython-input-14-c0efd521341e>, line 1)

In [10]:
type(model_mpg)

pandas.core.frame.DataFrame

In [11]:
## 2
model_mpg['mpg_change'] = model_mpg['cmb_mpg_2008'] - model_mpg['cmb_mpg']

In [12]:
## 3. Find the vehicle that improved the most
# Find the max mpg change, and then use query or indexing to see what model it is!

model_mpg['mpg_change'].argmax()

('PORSCHE 911 GT3', 'PORSCHE 911 GT3')